apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: zee5poc
  labels:
    app: zee5poc
    tier: backendservice
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/zee5-poc/zeepoc
    argocd-image-updater.argoproj.io/write-back-method: git:secret:default/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project:  default


  source:
    repoURL: https://github.com/kushalacc/manifest.git
    targetRevision: HEAD
    path: zee5poc

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace = true


    automated:
      selfHeal: true
      prune: true
